---
apiVersion: v1
kind: Secret
metadata:
  name: shovel-secret
type: Opaque
data:
  destUri: "amqp://172.16.100.74" # encoded value for shovel destination URI; to learn about how to construct a valid uri, see: https://www.rabbitmq.com/uri-spec.html
  srcUri: "amqp://localhost" # encoded value shove source URI