apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: pos-txn-monitor
  namespace: pos-edge
spec:
  serviceAccountName: kapp-ns-admin
  fetch:
    - git:
        url: https://github.com/mwright-pivotal/POSTxnMonitor
        ref: origin/main
        subPath: deploy/app-ytt
  template:
    - ytt:
        inline:
          paths:
            values.yaml: |
              #@data/values
              ---
              namespace: pos-edge
              image: harbor.eqix.vmwedge.com/apps/pos-txn-monitor-dotnet-wrightmi@sha256:5c79a78bb0156525ca7d68622f6ee2762809d798ce3e27db5c016f4fc1e62269
  deploy:
    - kapp: {}
