#@ load("@ytt:data", "data")

#@ def labels():
app: pos-txn-monitor
#@ end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: pos-txn-monitor-dotnet
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: pos-txn-monitor-dotnet
        image: #@ data.values.image
        ports:
        - name: http
          containerPort: #@ data.values.app_port
---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: pos-txn-monitor
  labels: #@ labels()
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: http
  selector: #@ labels()
