apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pos-txn-monitor-dotnet
  labels:
    app.kubernetes.io/part-of: tanzu-edge-pos
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/mwright-pivotal/POSTxnMonitor.git
      ref:
        branch: main

